### ISSUE TITLE
imshow function is broken in pre-compiled library.

### ISSUE THREAD

**Issue by navrkr** [cocoa-xu/evision#103]
I recently updated from elixir 1.0.0-dev to 1.0.9 version of Evision and everything is great till now, just tried getting the image as output and this error popped (Note: All the issue is with cvwait and imshow doesn't work without cvwait).

![IMG_20221011_070312_455](https://user-images.githubusercontent.com/68466584/194978218-2a2e6714-e063-4397-9d98-0f97484c74f4.jpg)

**Comment by cocoa-xu** [comment]
Actually I'm considering deprecating `Evision.HighGui` because it's hard to have full or even decent support for most functions, especially supporting these C++ callbacks for GUI events, in this module. 

And on the other hand, Erlang has builtin support for `:wx` (`:wx` will be available if `wxWidgets` can be found when compiling Erlang), and it would be easier to have other things, like buttons/sliders, available to use and they are all well tested.

**Comment by cocoa-xu** [comment]
Here is an example using `:wx` with `:evision` in Erlang, [evision_erlang_dnn_demo.erl](https://github.com/cocoa-xu/evision/blob/main/examples/evision_erlang_dnn_demo.erl), but it should be relatively easy to port it to elixir. Also, here is the corresponding [demo video](https://www.youtube.com/watch?v=YUJavLTcOMw) showing this example code.

**Comment by navrkr** [comment]
Thanks and i guess you can close the issue as you would remove HighGui
Module in later releases.

**Comment by cocoa-xu** [comment]
> Thanks and i guess you can close the issue as you would remove HighGui Module in later releases.

Actually, I'd like to say thank you @navrkr for giving me a chance to discuss this problem, which I've been thinking about a while ago.

> And on the other hand, ...

Even compiling OpenCV with GTK support, sometimes the `imshow` function does not really work as expected: the window(s) it opened will not respond to any GUI events until calling `waitKey` again. 

To make it as good as one would expect like the one in C++/Python, it would require perhaps a few weeks investigated in it. But I'm focusing on other aspects of this library right now, also I'm hesitating because I don't know if this would worth that amount time, as  `:wx` exists in Erlang and elixir, and one can even build a relatively complex GUI app with `:wx`.

**Comment by navrkr** [comment]
In maybe not worth of that much time as of now but it is basic
functionality one would expect from opencv library, so prioritise things
according to their importance and don't rush to new modules all at once,
have a checklist as you always do.

**Comment by Jagan3534** [comment]
we slice the img as shown you using in python code but we have doubt to divide cube to 9 parts does it possible or tesseract can detect the places of it 
with numbers could you help us

**Comment by navrkr** [comment]
> we slice the img as shown you using in python code but we have doubt to divide cube to 9 parts does it possible or tesseract can detect the places of it with numbers could you help us

This is the not right place to discuss as the issue is been closed by the developer and you need to ask developers of https://github.com/elixir-nx/nx for any issues and you can also contact me on private channels like telegram (id: @navrkr).
