### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by sanjaykv02** [cocoa-xu/evision#120]
Respected Ma'am \ Sir,
After updating evision, segmentation fault happened in the function Evision.findContours(Evision.mat, method, mode ).

`code snippet:-`

      iex(1)> path = "images/grid_1.png"
      "images/grid_1.png"
      iex(2)> {_, img_mat} = Evision.imread path
      {:ok,
           %Evision.Mat{
               channels: 3,
               dims: 2,
               raw_type: 16,
               ref: #Reference<0.2914473186.3120168976.115461>,
               shape: {1080, 1080, 3},
               type: {:u, 8}
      }}
      iex(3)> Evision.findContours(img_mat, 1, 1)
      Segmentation fault (core dumped)

**Comment by cocoa-xu** [comment]
Hi, the first thing is that please update your dependencies, `{:evision, "~> 0.1.14"}`, because based on the return value, you're using an outdated version. This will solve the Segmentation fault issue, and return an error message if you use the same code.

Secondly, and to solve the real issue, OpenCV `findContours` expects a binary image instead of a 3-channel BGR image. Please see the [online docs](https://hexdocs.pm/evision/Evision.html) or OpenCV's [tutorial](https://docs.opencv.org/4.x/d4/d73/tutorial_py_contours_begin.html).
