### ISSUE TITLE
Functions in `snake_case`

### ISSUE THREAD

**Issue by Wigny** [cocoa-xu/evision#134]
Is there any technical limitation that obligates having functions in `camelCase`? If not, I would like to suggest renaming the functions to use the `snake_case` convention.

**Comment by cocoa-xu** [comment]
In the very beginning, I tried to follow the `snack_case` convention in Elixir, but that would cause too many edge cases to deal with so that the converted function names are sane.

Meanwhile, using `smallCamelCase` usually only changes the initial letter of the function name -- it will cause less trouble when searching other OpenCV code examples written in C++/Python because it's easier to search ignore case than mapping between `snack_case` and `camelCase`.

I can understand that some people think `snack_case` should be used whenever possible, but, **for me and for this project only**, I honestly think that it is better to choose a way that can help more users, especially beginners, to actually use this library.

**Comment by Wigny** [comment]
I was looking for this explanation! That makes sense, thanks for sharing...

**Comment by cocoa-xu** [comment]
No worries! :D

And just to add an example of the edge cases, in C++ we have `cv::COLOR_BayerGR2RGBA`, and there could be at least 4 ways to map it to `snake_case`

- `color_bayer_gr_2_rgba`
- `color_bayergr_2_rgba`
- `color_bayergr2rgba`
- `color__bayer_gr2_rgba` <= `Macro.underscore("COLOR_BayerGR2RGBA")`

It might be easy to choose any of these for this example, but applying the same processing for some other functions might make them hard to read because the converted `snake_case` name might be strange or hard to read. 

`COLOR_BayerGR2RGBA` is one of the examples that I don't really feel quite comfortable with any of these transformations -- they just look weird or hard to read.

And there are a few dozen of them that require us to look ahead to know if and where to put the `_` and how many consecutive letters should be transformed into lower cases.
