### ISSUE TITLE
text recogintion error

### ISSUE THREAD

**Issue by dkuku** [cocoa-xu/evision#144]
I'm just playing with evision in livebook - nice work.
I'm getting errors when trying text recognition with lower precision model 16 or 8 bit.
![image](https://user-images.githubusercontent.com/904179/208164907-da363274-f77a-4d0f-bfb0-827d4ee34e64.png)

**Comment by cocoa-xu** [comment]
Hi @dkuku, thanks for reporting the bug. The issue with `charset_info/1` has been fixed. 

However, after looking into this CRNN model, I found that they (these FP16 variants) were not supported until [opencv/opencv #22337](https://github.com/opencv/opencv/pull/22337), which was after the release date of OpenCV 4.6.0. Another ref link [https://github.com/opencv/opencv/issues/18735#issuecomment-1273125970](https://github.com/opencv/opencv/issues/18735#issuecomment-1273125970).

So I'll hide these CRNN FP16 models until the next version of OpenCV is released.

I also hide the `CRNN CH (INT8)` and `CRNN EN (INT8)` models because OpenCV 4.6.0 seemed to have problems loading/parsing them even with the `demo.py` script in the official opencv_zoo repo. I haven't dug into why they are problematic, but hopefully, they should be supported in the next version of OpenCV. :)

**Comment by cocoa-xu** [comment]
I released v0.1.24, and the issue related to `charset/1` should be solved. I'll leave this issue open to track CRNN FP16 models. :)

**Comment by dkuku** [comment]
thanks for the update, great work.

**Comment by cocoa-xu** [comment]
INT8 models work now, but there still seem to be some issues with FP16 models.

```shell
$ pip3 install -U opencv-python
Requirement already satisfied: opencv-python in /Users/cocoa/Library/Python/3.9/lib/python/site-packages (4.7.0.68)

$ python3 -c 'import cv2; print(cv2.version.opencv_version)'
4.7.0.68

$ cd opencv_zoo/models/text_recognition_crnn

$ # INT8 model works
$ python3 demo.py -i demo.png -m text_recognition_CRNN_EN_2022oct_int8.onnx -c charset_36_EN.txt
Resutls saved to result.jpg

$ # FP16 model will fail
$ python3 demo.py -i demo.png -m text_recognition_CRNN_EN_2022oct_fp16.onnx -c charset_36_EN.txt
[ WARN:0@0.018] global onnx_graph_simplifier.cpp:804 getMatFromTensor DNN: load FP16 model as FP32 model, and it takes twice the FP16 RAM requirement.
[ERROR:0@0.022] global onnx_importer.cpp:1054 handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [Conv]:(onnx_node!Conv_0) from domain='ai.onnx'
Traceback (most recent call last):
  File "/Users/cocoa/Git/opencv_zoo/models/text_recognition_crnn/demo.py", line 63, in <module>
    recognizer = CRNN(modelPath=args.model, charsetPath=args.charset)
  File "/Users/cocoa/Git/opencv_zoo/models/text_recognition_crnn/crnn.py", line 17, in __init__
    self._model = cv.dnn.readNet(self._model_path)
cv2.error: OpenCV(4.7.0) /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Conv@ai.onnx]:(onnx_node!Conv_0) parse error: OpenCV(4.7.0) /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/modules/dnn/src/layers/convolution_layer.cpp:398: error: (-215:Assertion failed) inputs.size() != 0 in function 'getMemoryShapes'
```

**Comment by cocoa-xu** [comment]
Hi @dkuku, FP16 CRNN models are working now. I'll do a release (v0.1.37) at sometime this week! I'll let you know once it's shipped on hex.pm.

<img width="679" alt="Screenshot 2024-02-17 at 00 24 11" src="https://github.com/cocoa-xu/evision/assets/89497197/81e2ea0c-5e79-4049-874d-dea6bcb93e7c">
