### ISSUE TITLE
Not able to use Evision Library with Elixir 1.14.4-otp25

### ISSUE THREAD

**Issue by Jitesh-Srivastava** [cocoa-xu/evision#196]
Hi creator,
I have did the installation process of Evision v0.1.15 with command "{:evision, "~> 0.1.15", github: "cocoa-xu/evision", branch: "main"}" with the exporting of "export EVISION_PREFER_PRECOMPILED=false" and installing cmake but always find this error and could not able to resolve this. Please help to resolve the error

![image](https://github.com/cocoa-xu/evision/assets/74318565/d5ce1b44-6421-4085-bdbb-e105bfec6dc8)

Even i've tried to delete and rebuilt it

**Comment by cocoa-xu** [comment]
Hi @Jitesh-Srivastava, I'll look into this later today! And could you please let me know the CMake's version on your machine?

**Comment by Jitesh-Srivastava** [comment]
It's showing cmake version is 3.10.2

**Comment by cocoa-xu** [comment]
> @cocoa-xu It's showing cmake version is 3.10. Also if I am trying to use "export EVISION_PREFER_PRECOMPILED=true" then it shows failed to load nif library:
> 
> ![image](https://user-images.githubusercontent.com/74318565/249712218-a4fa97e5-e844-4004-a64e-7ad4205a8439.png)

Oh I see, the Linux precompiled binaries were compiled on Ubuntu 20.04, which links to GLIBC 2.29, and it seems that you were using an old Linux distro. Could you please let me know your OS and its version?

**Comment by Jitesh-Srivastava** [comment]
I am using Linux 18.04

**Comment by cocoa-xu** [comment]
Sorry I'm afraid that you may need to build it from source for now. The Ubuntu 18.04 GitHub action runner has been deprecated since 12/1/22 [link](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/).

One possible way to fix this is to use zig as the C++ compiler, and then we can specify the version of glibc it links to.

However, Ubuntu 18.04 itself is also deprecated since April 30, 2023. So I'm not sure if it's worth to make all the changes for it...

**Comment by cocoa-xu** [comment]
<img width="570" alt="Screenshot 2023-08-01 at 09 09 47" src="https://github.com/cocoa-xu/evision/assets/89497197/1c1d60ae-cf5c-475a-8a51-9f866effe6b5">

It should work now, w/ and w/o contrib modules, except for the CUDA ones.
