### ISSUE TITLE
Has Evision.Backend been removed?

### ISSUE THREAD

**Issue by RyoWakabayashi** [cocoa-xu/evision#214]
Evision.Backend seems to be missing

https://hexdocs.pm/evision/0.1.32/Evision.BFMatcher.html

**Comment by cocoa-xu** [comment]
Sorry that it did not compile correctly. I just retired it and will do 0.1.33 today.

**Comment by kipcole9** [comment]
It is there but Code.ensure_loaded? Returns false depending on compilation pretty. I don't think that check is required - when I remove it everything completely fine since Evision is in the library.

**Comment by cocoa-xu** [comment]
Yeah, it was there because I was trying to fetch all precompiled binaries on a new remote Linux machine without compiling it before, so there were a lot of warnings and errors. 

I have to add that check to bypass it in order to fetch the precompiled binaries for that machine, get all the generated Elixir modules and then the module `Evision` should be there, fixing the warnings or errors during the compilation. After that, I tried to revert all these checks in multiple files, but I missed this one on that machine.

**Comment by kipcole9** [comment]
Do you think you could also relax the requirement for progress_bar to allow ~> 2.0 and ~> 3.0 ?  Current bumblebee conflicts with its requirement for ~> 2.0 (except on main branch) so I can't use both latest Evision and latest bumblebee together.

**Comment by kipcole9** [comment]
> Oh okay I'll add that!

Thank you @cocoa-xu.  When I configure Nx and Bumblebee from GitHub (in order to be able to use evision 0.1.31) and then remove the `Code.is_loaded?/1` check on `Evision.Backend`, all the tests in `Image` pass.  Including precompiled binaries for Elixir 1.15 and OTP 26.

Thanks very much for all the hard work, it's really appreciated. Looking forward to `0.1.33`!

**Comment by cocoa-xu** [comment]
0.1.33 is shipped! This issue should be fixed~

**Comment by cocoa-xu** [comment]
As this issue should be addressed in v0.1.33. I'm closing it for now. Please feel free to reopen it if it didn't work.
