### ISSUE TITLE
Evision.boxPoints/1 is not working

### ISSUE THREAD

**Issue by navrkr** [cocoa-xu/evision#99]
It is asking for a map as input but we are getting a tuple as output for minAreaRect

*** (FunctionClauseError) no function clause matching in Evision.boxPoints/1    
    
    The following arguments were given to Evision.boxPoints/1:
    
        # 1
        {{224.0, 262.5}, {343.0, 344.0}, 90.0}
    
    Attempted function clauses (showing 1 out of 1):
    
        def boxPoints(box) when is_reference(box) or is_map(box) and is_map_key(box, :__struct__) and is_atom(:erlang.map_get(:__struct__, box))
    
    (evision 0.1.7-dev) lib/generated/evision.ex:6346: Evision.boxPoints/1

**Comment by cocoa-xu** [comment]
Hi @navrkr, I've fixed the function guard generation in v0.1.9, and the latest version is available on hex.pm. 

```
def deps do
  [
    {:evision, "~> 0.1.9"}
  ]
end
```

The hex.pm release will use precompiled binaries by default. If you prefer to compile it locally, please set the environment variable `EVISION_PREFER_PRECOMPILED` to `false` before `mix compile` or `iex -S mix`.

One more note is that you might need to delete the `_build/${MIX_ENV}/lib/evision/evision.so` (`MIX_ENV` is `dev` by default) if you are okay with using precompiled binaries. Because the deployer will not override existing files if this file exists.

#### Bug fixes
- Support parsing `RefWrapper<T> (&value)[N]` from list or tuple. ([#99](https://github.com/cocoa-xu/evision/issues/99))

  See the function in `c_src/evision.cpp`.

  ```cpp
  bool parseSequence(ErlNifEnv *env, ERL_NIF_TERM obj, RefWrapper<T> (&value)[N], const ArgInfo& info)
  ```

  ```elixir
  # `RotatedRect` has to be a tuple, {centre, size, angle}
  Evision.boxPoints!({{224.0, 262.5}, {343.0, 344.0}, 90.0})

  # while `Point`/`Size` can be either a list, `[x, y]`, or a tuple, `{x, y}`
  Evision.boxPoints!({[224.0, 262.5], [343.0, 344.0], 90.0})
  ```

- Fixed the mapping from a type to the corresponding function guard in `py_src/helper.py`. ([#99](https://github.com/cocoa-xu/evision/issues/99))

**Comment by cocoa-xu** [comment]
As the patches above should fix this issue, I'll close this one for now. 

Please feel free to reopen it if there is any other issue with `Evision.boxPoints/1`, also don't hesitate to open a new issue if you encounter other problems. :)

**Comment by navrkr** [comment]
Yeah issue resolved. Can you help me with image ROI method I'm getting this error when try to solve it. 
![Screenshot from 2022-10-09 23-25-17](https://user-images.githubusercontent.com/68466584/194801647-f26af5d5-5f55-4bba-ad20-17f71c6d0631.png)

**Comment by kipcole9** [comment]
Hmmm thats really impossible to read. May I suggest you open a separate issue (since this one is resolved) and cut/paste the text into a code block rather than a screen shot. It makes it almost impossible for the maintainer to work with your example if its a screenshot.

**Comment by navrkr** [comment]
Yeah sure.
